### ISSUE TITLE
Viz II

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#1623]
- [ ] Add support for HIPIE properties in property editor
- [ ] Source code editor (ECL + DUD + KEL etc.)
- [ ] Push mappings into properties.
- [ ] HIPIE ability to read persist strings
- [ ] Publish Events and allow entry.
- [ ] Ramps execution graph
- [ ] Move marshaller to its own project

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
