### ISSUE TITLE
Marshaller / Mega Chart Title Enhancements

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2274]
Need a way to let the user define how the title displays the current filter criteria:

 - [x] Ability to disable filter information: https://github.com/hpcc-systems/Visualization/issues/2242
 - [x] Remap IDs to Labels: https://github.com/hpcc-systems/Visualization/issues/2243
 - [ ] Dash for ranges: https://github.com/hpcc-systems/Visualization/issues/2248

**Comment by GordonSmith** [comment]
Closing (no need for the placeholder parent issue)
