### ISSUE TITLE
EPIC:  Graph2 Enhancements

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#3516]
- [ ] [Legend](https://github.com/hpcc-systems/Visualization/issues/3515)
- [ ] [Tables](https://github.com/hpcc-systems/Visualization/issues/3517)
- [ ] [Filtering](https://github.com/hpcc-systems/Visualization/issues/3518)
